name: Lint with Flake8

on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out your code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Replace with your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Install Flake8

      - name: Run Flake8
        run: |
          flake8 .
